# Site settings
# vim: nospell
port: 4000
output: _dist
title: one Land
description: The safe place on the (inter)net
email: michelcombes@advancementofcivilizationeffort.org
baseurl: ""
url: "//oneland.gq" # the base hostname & protocol for your site
googledocid: 1PPeZqr5KTlXhRMlqiEuXVychnTtrtEfECZDcwfIYaH4
framaid: pad_56159

exclude:
 - .org
 - _site
 - Gemfile
 - Gemfile.lock
 - travis.sh
